spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/resumes_db
    username: postgres
    password: postgres
    pool-size: 30
#    driver-class-name: org.postgresql.Driver